name: Swift

on:
    push:
        branches: [ master ]
    pull_request:
        branches: [ master ]

jobs:
    test:
        runs-on: macos-latest
        steps:
            - uses: actions/checkout@v2
            - name: Test Chatto
              run: ./scripts/test.sh chatto
            - name: Test ChattoAdditions
              run: ./scripts/test.sh additions
            - name: Test ChattoApp
              run: ./scripts/test.sh app
